/* Approved v0.72 manifest recipes, kept private because native table functions
 * cannot be hooked. Public publication uses the duel recipe table only. */
typedef struct { int id; unsigned short result; int conditional; TablesRitualRequirement q[3]; } CompatPrivateRecipe;
static const CompatPrivateRecipe compat_private_recipes[] = {
{665,362,1,{{.card=296,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=1000,.max_attack=-1,.max_defense=2999,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=1},{.card=0,.min_attack=0,.min_defense=1000,.max_attack=-1,.max_defense=2999,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=1}}},
{666,357,1,{{.card=101,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=0,.max_attack=1599,.max_defense=1799,.type=CARD_TYPE_DRAGON,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=0,.max_attack=1599,.max_defense=1799,.type=CARD_TYPE_DRAGON,.min_level=-1,.max_level=-1,.defense_gt_attack=0}}},
{695,715,1,{{.card=166,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=0,.max_attack=1999,.max_defense=2349,.type=CARD_TYPE_MACHINE,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=0,.max_attack=1999,.max_defense=2349,.type=CARD_TYPE_FIEND,.min_level=-1,.max_level=-1,.defense_gt_attack=0}}},
{677,702,1,{{.card=14,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=0,.max_attack=1999,.max_defense=1849,.type=CARD_TYPE_PLANT,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=0,.max_attack=1999,.max_defense=1849,.type=CARD_TYPE_PYRO,.min_level=-1,.max_level=-1,.defense_gt_attack=0}}},
{674,365,0,{{.card=186,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=261,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=595,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0}}},
{696,717,1,{{.card=52,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=533,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=0,.max_attack=2449,.max_defense=2549,.type=CARD_TYPE_INSECT,.min_level=-1,.max_level=-1,.defense_gt_attack=0}}},
{667,374,0,{{.card=371,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=372,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=373,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0}}},
{692,710,1,{{.card=451,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=0,.max_attack=2549,.max_defense=2499,.type=CARD_TYPE_AQUA,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=0,.max_attack=2549,.max_defense=2499,.type=CARD_TYPE_AQUA,.min_level=-1,.max_level=-1,.defense_gt_attack=0}}},
{700,718,1,{{.card=441,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=0,.max_attack=2349,.max_defense=2149,.type=CARD_TYPE_FISH,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=0,.max_attack=2349,.max_defense=2149,.type=CARD_TYPE_FISH,.min_level=-1,.max_level=-1,.defense_gt_attack=0}}},
{691,706,1,{{.card=294,.min_attack=0,.min_defense=0,.max_attack=-1,.max_defense=-1,.type=-1,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=0,.max_attack=2349,.max_defense=2399,.type=CARD_TYPE_FIEND,.min_level=-1,.max_level=-1,.defense_gt_attack=0},{.card=0,.min_attack=0,.min_defense=0,.max_attack=2349,.max_defense=2399,.type=CARD_TYPE_DRAGON,.min_level=-1,.max_level=-1,.defense_gt_attack=0}}},
};
static int compat_private_requirements(int id,TablesRitualRequirement *q,unsigned short *result)
{ unsigned i;for(i=0;i<sizeof(compat_private_recipes)/sizeof(compat_private_recipes[0]);++i)if(compat_private_recipes[i].id==id&&compat_private_recipes[i].conditional){memcpy(q,compat_private_recipes[i].q,sizeof(compat_private_recipes[i].q));*result=compat_private_recipes[i].result;return 1;}return 0;}
static int compat_private_recipe(int id,unsigned short *row)
{ unsigned i;int j;for(i=0;i<sizeof(compat_private_recipes)/sizeof(compat_private_recipes[0]);++i)if(compat_private_recipes[i].id==id&&!compat_private_recipes[i].conditional){row[0]=id;for(j=0;j<3;++j)row[j+1]=compat_private_recipes[i].q[j].card;row[4]=compat_private_recipes[i].result;row[5]=0;return 1;}return -1;}
