name: credits
sha1: a13276b039a4991c119f8911c50bf114f3822e16

options:
  basename: credits
  base_path: ../../..
  target_path: tmp/overlays/credits/module.bin
  elf_path: tmp/overlays/credits/build/credits.elf
  platform: psx
  compiler: PSYQ
  endianness: little

  asm_path: tmp/overlays/credits/asm
  src_path: src
  build_path: tmp/overlays/credits/build
  asset_path: tmp/overlays/credits/assets
  cache_path: tmp/overlays/credits/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings

  ld_script_path: tmp/overlays/credits/credits.ld
  generated_asm_macros_directory: tmp/overlays/credits/include
  lib_path: tmp/overlays/credits/lib
  o_path: tmp/overlays/credits/build
  undefined_funcs_auto_path: tmp/overlays/credits/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/credits/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/slus_01411/overlays/credits_symbols.txt

  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2

  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x80180000
    align: 4
    subsegments:
      - [0x0, data, overlays/credits/module_header]

  - name: update_jump_table
    type: code
    start: 0x79C
    vram: 0x8018079C
    align: 4
    subsegments:
      - [0x79C, .rodata, overlays/credits/update]

  - name: module
    type: code
    start: 0x7B0
    vram: 0x801807B0
    align: 4
    subsegments:
      - [0x7B0, c, overlays/credits/init]
      - [0xA24, c, overlays/credits/update]
      - [0xF58, c, overlays/credits/text]
      - [0x173C, c, overlays/credits/draw]
      - [0x1C4C, c, overlays/credits/lines]
      - [0x1D38, data, overlays/credits/data]

  - [0x8000]
