#!/usr/bin/env python3
"""Embed the controller PNG so native executables do not depend on asset paths.

Only the chunks that make the picture are embedded (KEEP: the image data and
what changes how libpng decodes it), so the pixels are the file's. The file
also carries a C2PA manifest (the image tool's provenance: certificates and a
signature, 23 KB), which in an executable looks to virus scanners'
heuristics like an embedded signed blob.
"""
import struct
import zlib
from pathlib import Path

KEEP = {b"IHDR", b"PLTE", b"tRNS", b"gAMA", b"cHRM", b"sRGB", b"iCCP", b"sBIT", b"IDAT", b"IEND"}
root = Path(__file__).resolve().parents[2]
source = root / "src/pc/assets/ps1-controller.png"
original = source.read_bytes()
data, at = bytearray(original[:8]), 8
while at < len(original):
    length, kind = struct.unpack(">I4s", original[at:at + 8])
    chunk = original[at:at + 12 + length]
    if zlib.crc32(chunk[4:8 + length]) != struct.unpack(">I", chunk[8 + length:])[0]:
        raise SystemExit(f"{source}: chunk {kind!r} at {at} fails its CRC")
    if kind in KEEP:
        data += chunk
    at += 12 + length
out = root / "src/pc/assets/ps1_controller_png.h"
with out.open("w") as f:
    f.write("/* Generated by tools/pc/embed_controls_art.py. Do not edit. */\n")
    f.write("static const unsigned char ps1_controller_png[] = {\n")
    for i in range(0, len(data), 24):
        f.write("    " + ",".join(str(b) for b in data[i:i+24]) + ",\n")
    f.write("};\n")
print(f"Embedded {len(data)} of {len(original)} bytes (the picture's chunks) from {source.relative_to(root)}")
